version: '3'
services:
  client:
    build:
      context: ./client  # Path to the client folder
    volumes:
      - ./types:/app/types  # Mount types from the root to the container's /app/types
    ports:
      - "5173:5173"
    working_dir: /app
    command: yarn dev
